#!/usr/bin/env python3
"""
Differential Windowed Protection Score Analysis
===============================================

This script performs differential analysis of per-region Windowed Protection
Score (WPS) metrics between two groups of cfDNA samples. It identifies
genomic regions where a chosen WPS metric (by default the 170 bp spectral
power ``power_170``) differs significantly between the groups, using
Wilcoxon rank-sum tests with Benjamini-Hochberg FDR correction.

The input is the per-sample per-region WPS metrics CSV produced by
``pyfrag.py scores`` (``wps_metrics_{name}.csv``), which is generated by
:func:`pyfraglib.scores.wps_region_metrics`.

Input format:
    JSON configuration file with two fields:
    - "group_a": List of wps_metrics_*.csv file paths for group A samples
    - "group_b": List of wps_metrics_*.csv file paths for group B samples

    CSV files must have WPS metrics format with at least the columns:
    - region, n_peaks, median_peak_dist, median_prom, median_width,
      power_170, n_positions

Output:
    - Differential analysis results as CSV
    - Volcano plot showing effect sizes and significance
    - Effect-size histogram

Usage:
    python differential_wps.py -c config.json -o output_dir/ \
                               --metric power_170

License
-------
Copyright (C) 2026 Daniel Schütte, daniel.schuette@iccb-cologne.org

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version. This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
more details. You should have received a copy of the GNU General Public
License along with this program. If not, see <https://www.gnu.org/licenses/>.
"""
import argparse
import json
import logging
import os
import sys
import pyfraglib

import numpy as np
import numpy.typing as npt
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path
from typing import Final, NoReturn
from scipy import stats
from statsmodels.stats.multitest import fdrcorrection  # type: ignore

version_string: Final[str] = \
    "differential_wps v{} (running on Python v{})" \
    .format(pyfraglib.__version__, sys.version.split(" ")[0])
LOGGER_NAME: Final[str] = "differential_wps"
SUPPORTED_METRICS: Final[list[str]] = [
    "power_170", "n_peaks", "median_peak_dist",
    "median_prom", "median_width",
]


def fail(msg: str, logger: logging.Logger) -> NoReturn:
    """
    Log a fatal error message and exit the program.

    Args:
        msg: Error message to log
        logger: Logger instance to use for logging

    Raises:
        SystemExit: Always exits with code 1
    """
    logger.fatal(msg)
    sys.exit(1)


def load_config(
    config_path: str, logger: logging.Logger
) -> dict[str, list[str]]:
    """
    Load JSON configuration file with group definitions.

    Args:
        config_path: Path to JSON configuration file
        logger: Logger instance for output

    Returns:
        Dictionary with 'group_a' and 'group_b' file lists

    Raises:
        SystemExit: If config file is invalid or missing required fields
    """
    if not os.path.exists(config_path):
        fail("config file '{}' does not exist".format(config_path), logger)

    try:
        with open(config_path, "r") as f:
            config: dict[str, object] = json.load(f)
        required_fields: list[str] = ["group_a", "group_b"]
        for field in required_fields:
            if field not in config:
                fail("missing required field '{}' in config".format(field),
                     logger)

        group_a: list[str] = config["group_a"]  # type: ignore
        group_b: list[str] = config["group_b"]  # type: ignore
        if not isinstance(group_a, list) or not isinstance(group_b, list):
            fail("group_a and group_b must be lists of file paths", logger)

        if len(group_a) == 0 or len(group_b) == 0:
            fail("both groups must contain at least one file", logger)

        all_files: list[str] = group_a + group_b
        for file_path in all_files:
            if not os.path.exists(file_path):
                fail("file '{}' does not exist".format(file_path), logger)

        logger.info("found files: {} in group A, {} in group B".format(
            len(group_a), len(group_b)))
        return {"group_a": group_a, "group_b": group_b}

    except json.JSONDecodeError as e:
        fail("invalid JSON in config file: {}".format(e), logger)
    except Exception as e:
        fail("error loading config file: {}".format(e), logger)


def load_wps_metric_matrix(
    csv_files: list[str], metric: str, group_name: str,
    logger: logging.Logger,
) -> pd.DataFrame:
    """
    Load per-region WPS metrics from CSV files into a samples x regions
    matrix for the chosen metric.

    Args:
        csv_files: List of per-sample WPS metrics CSV paths (as produced by
            ``pyfrag.py scores``).
        metric: Column name to extract (e.g. ``power_170``).
        group_name: Name of the group (for logging).
        logger: Logger instance for output.

    Returns:
        DataFrame with one row per sample and one column per region. Missing
        values are kept as ``NaN``.

    Raises:
        SystemExit: If CSVs are malformed or do not carry the requested
            metric.
    """
    logger.info("loading {} files for group '{}'".format(
        len(csv_files), group_name))

    required_cols: set[str] = {"region", metric}

    sample_series: dict[str, pd.Series] = {}  # type: ignore
    for csv_file in csv_files:
        sample_name: str = Path(csv_file).stem
        logger.debug("loading data from '{}'".format(csv_file))

        try:
            df: pd.DataFrame = pd.read_csv(csv_file)
        except Exception as e:
            fail("error reading CSV file '{}': {}".format(csv_file, e), logger)

        missing: set[str] = required_cols - set(df.columns)
        if missing:
            fail("CSV '{}' is missing required columns: {}".format(
                csv_file, sorted(missing)), logger)

        s: pd.Series = (  # type: ignore
            df.drop_duplicates("region")
              .set_index("region")[metric]
              .astype(float)
        )
        sample_series[sample_name] = s

    matrix: pd.DataFrame = pd.DataFrame(sample_series).T
    matrix.index.name = "sample"
    logger.debug("group '{}' matrix: {} samples × {} regions".format(
        group_name, matrix.shape[0], matrix.shape[1]))
    return matrix


def perform_differential_analysis(
    group_a_data: pd.DataFrame, group_b_data: pd.DataFrame, metric: str,
    min_samples_per_group: int, logger: logging.Logger,
) -> pd.DataFrame:
    """
    Perform differential analysis between two groups using Wilcoxon tests.

    Args:
        group_a_data: Samples × regions matrix for group A.
        group_b_data: Samples × regions matrix for group B.
        metric: Metric name (carried into the results for provenance).
        min_samples_per_group: Minimum number of non-``NaN`` values required
            in each group for a region to be tested.
        logger: Logger instance for output.

    Returns:
        DataFrame with one row per tested region containing group means and
        standard deviations, median fold change, Wilcoxon p-value and
        FDR-adjusted p-value, and a rank-biserial effect size.
    """
    common_regions: list[str] = sorted(
        set(group_a_data.columns) & set(group_b_data.columns)
    )
    if len(common_regions) == 0:
        fail("no regions are shared between the two groups", logger)
    logger.info("analyzing {} shared regions".format(len(common_regions)))

    results: list[dict[str, object]] = []
    for region in common_regions:
        a_vals: npt.NDArray[np.float64] = \
            group_a_data[region].to_numpy(dtype=float)
        b_vals: npt.NDArray[np.float64] = \
            group_b_data[region].to_numpy(dtype=float)

        a_valid: npt.NDArray[np.float64] = a_vals[~np.isnan(a_vals)]
        b_valid: npt.NDArray[np.float64] = b_vals[~np.isnan(b_vals)]
        if (len(a_valid) < min_samples_per_group or
                len(b_valid) < min_samples_per_group):
            continue

        mean_a: float = float(np.mean(a_valid))
        mean_b: float = float(np.mean(b_valid))
        std_a: float = float(np.std(a_valid))
        std_b: float = float(np.std(b_valid))
        median_a: float = float(np.median(a_valid))
        median_b: float = float(np.median(b_valid))
        # +1 pseudocount keeps log-fold-change finite for metrics that can
        # legitimately reach zero (e.g. ``n_peaks``).
        log_fold_change: float = float(np.log2((mean_b + 1) / (mean_a + 1)))

        try:
            statistic, p_value = stats.mannwhitneyu(
                a_valid, b_valid, alternative="two-sided"
            )
            n_a: int = len(a_valid)
            n_b: int = len(b_valid)
            u_statistic: float = float(statistic)
            effect_size: float = 1.0 - (2.0 * u_statistic) / (n_a * n_b)
        except ValueError:
            p_value = np.float64(1.0)
            effect_size = 0.0

        results.append({
            "region": region,
            "metric": metric,
            "n_group_a": int(len(a_valid)),
            "n_group_b": int(len(b_valid)),
            "mean_group_a": mean_a,
            "mean_group_b": mean_b,
            "std_group_a": std_a,
            "std_group_b": std_b,
            "median_group_a": median_a,
            "median_group_b": median_b,
            "log_fold_change": log_fold_change,
            "p_value": float(p_value),
            "effect_size": effect_size,
        })

    if len(results) == 0:
        fail("no regions passed the min-samples-per-group filter", logger)

    results_df: pd.DataFrame = pd.DataFrame(results)
    rejected, p_adjusted = \
        fdrcorrection(results_df["p_value"].values, alpha=0.05)
    results_df["p_adjusted"] = p_adjusted
    results_df["significant"] = rejected
    results_df = results_df.sort_values("p_value")
    n_significant: int = int(results_df["significant"].sum())

    logger.info("found {} significant regions after FDR correction".format(
        n_significant))
    return results_df


def create_differential_plots(
    results_df: pd.DataFrame, metric: str, out_dir: str,
    logger: logging.Logger,
) -> None:
    """
    Create visualization plots for differential analysis results.

    Args:
        results_df: DataFrame with differential analysis results.
        metric: Metric name used to label axes.
        out_dir: Output directory for plots.
        logger: Logger instance for output.
    """
    neg_log10_p_adj: npt.NDArray[np.float64] = \
        -np.log10(results_df["p_adjusted"].values + 1e-100)  # type: ignore
    colors: list[str] = [
        "red" if sig else "gray" for sig in results_df["significant"]
    ]

    fig1, ax1 = plt.subplots(figsize=(10, 8))
    ax1.scatter(
        results_df["log_fold_change"], neg_log10_p_adj,
        c=colors, alpha=0.7, s=30
    )
    ax1.axhline(
        y=-np.log10(0.05), color="black",
        linestyle="--", alpha=0.5, label="FDR = 0.05"
    )
    ax1.axvline(x=0, color="black", linestyle="-", alpha=0.3)
    ax1.set_xlabel(
        "Log2 Fold Change (Group B / Group A)  [{}]".format(metric)
    )
    ax1.set_ylabel("-log10(FDR-adjusted p-value)")
    ax1.set_title(
        "Volcano Plot: Differential WPS Analysis ({})".format(metric)
    )
    ax1.legend(["FDR = 0.05", "FDR < 0.05", "FDR ≥ 0.05"])
    ax1.grid(True, alpha=0.3)

    top_significant: pd.DataFrame = \
        results_df[results_df["significant"]].head(15)
    for _, row in top_significant.iterrows():
        if row["p_adjusted"] < 0.01:
            ax1.annotate(
                str(row["region"]),
                (row["log_fold_change"],
                 -np.log10(row["p_adjusted"] + 1e-100)),
                xytext=(5, 5), textcoords="offset points",
                fontsize=8, alpha=0.8
            )
    plt.tight_layout()

    volcano_path: str = os.path.join(
        out_dir, "differential_wps_volcano_{}.png".format(metric)
    )
    fig1.savefig(volcano_path, dpi=300, bbox_inches="tight")
    logger.info("saved volcano plot to '{}'".format(volcano_path))
    plt.close(fig1)

    fig2, ax2 = plt.subplots(figsize=(10, 6))
    sig_effects: npt.NDArray[np.float64] = \
        results_df[
            results_df["significant"]  # type: ignore
        ]["effect_size"].values
    nonsig_effects: npt.NDArray[np.float64] = \
        results_df[
            ~results_df["significant"]  # type: ignore
        ]["effect_size"].values

    ax2.hist(nonsig_effects, bins=30, alpha=0.7,
             label="Non-significant", color="gray")
    ax2.hist(sig_effects, bins=30, alpha=0.7, label="Significant", color="red")
    ax2.set_xlabel("Effect Size (Rank-biserial correlation)")
    ax2.set_ylabel("Number of Regions")
    ax2.set_title("Distribution of Effect Sizes ({})".format(metric))
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    effect_path: str = os.path.join(
        out_dir, "differential_wps_effect_sizes_{}.png".format(metric)
    )
    fig2.savefig(effect_path, dpi=300, bbox_inches="tight")
    logger.info("saved effect size plot to '{}'".format(effect_path))
    plt.close(fig2)


def create_argparser() -> argparse.ArgumentParser:
    """
    Create and configure the argument parser.

    Returns:
        Configured ArgumentParser instance.
    """
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        prog="differential_wps",
        description="Perform differential analysis of per-region WPS "
                    "metrics.",
        epilog="{}. Licensed under GPLv3.".format(version_string))

    parser.add_argument(
        "-c", "--config", type=str, dest="config_file", required=True,
        help="JSON configuration file with group_a and group_b file lists")

    parser.add_argument(
        "-o", "--out-dir", type=str, dest="out_dir",
        default="differential_wps_output",
        help="Output directory for results and plots (default: "
        "differential_wps_output)")

    parser.add_argument(
        "--metric", type=str, dest="metric", default="power_170",
        choices=SUPPORTED_METRICS,
        help="Per-region WPS metric to test. Must be a column in the input "
        "CSVs. Default: power_170")

    parser.add_argument(
        "--min-samples-per-group", type=int, dest="min_samples_per_group",
        default=3, help="Minimum non-NaN values per group to test a region "
        "(default: 3)")

    parser.add_argument(
        "-v", "--verbose", action="store_true", dest="is_verbose",
        default=False, help="Enable verbose logging")

    return parser


def main() -> None:
    """
    Main function for the differential WPS analysis script.
    """
    logger: logging.Logger = logging.getLogger(LOGGER_NAME)
    parser: argparse.ArgumentParser = create_argparser()
    args: argparse.Namespace = parser.parse_args()

    level: int
    is_verbose: Final[bool] = args.is_verbose
    if is_verbose:
        level = logging.DEBUG
    else:
        level = logging.INFO
    logging.basicConfig(level=level)
    logger.setLevel(level)
    logger.info("starting differential WPS analysis")
    logger.info(version_string)

    out_dir: str = args.out_dir
    if not os.path.exists(out_dir):
        logger.info("creating output directory '{}'".format(out_dir))
        os.makedirs(out_dir, exist_ok=True)

    metric: str = args.metric
    config_file: str = args.config_file
    config: dict[str, list[str]] = load_config(config_file, logger)
    group_a_data: pd.DataFrame = load_wps_metric_matrix(
        config["group_a"], metric, "A", logger
    )
    group_b_data: pd.DataFrame = load_wps_metric_matrix(
        config["group_b"], metric, "B", logger
    )

    results_df: pd.DataFrame = perform_differential_analysis(
        group_a_data, group_b_data, metric,
        args.min_samples_per_group, logger,
    )
    results_path: str = os.path.join(
        out_dir, "differential_wps_results_{}.csv".format(metric)
    )
    results_df.to_csv(results_path, index=False)
    logger.info("saved differential results to '{}'".format(results_path))
    create_differential_plots(results_df, metric, out_dir, logger)


if __name__ == "__main__":
    main()
